### ISSUE TITLE
fix: metabolite id compliance with cobrapy

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#101]
### Description of the issue:
Following up on [this tweet](https://twitter.com/willigo09/status/986329883570855937), a small annoyance for cobrapy users of the `.xml` file is the metabolite id format `metID[comp]` from COBRA toolbox, as the characters `[]` are stored in an odd way for SBML compatibility, and then read literally by cobrapy.

#### Example:
* Original metabolite ID: `s_0001[c]`
* Stored in .xml file/opened by cobrapy: `s_0001__91__c__93__`
* How it **should** be opened by cobrapy: `s_0001_c`

@tpfau are there any plans of making te resulting `.xml` file compatible in this sense with cobrapy? Is there any other way of storing the compartment information in the metabolite id other than with `[]` characters?

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/YeastMetabolicNetwork-GEM#required-software) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/YeastMetabolicNetwork-GEM) about the issue

**Comment by tpfau** [comment]
@BenjaSanchez:
There are plans (from my side), to make the ID irrelevant for all of this and store the actual ID in a different field. please have a look here:
https://github.com/opencobra/schema/issues/6
From my point of view, since there are no clear definitions on what ids specific compartments have, and all the additional data there is in an ID, I decided to make export to SBML as unambigous as possible, by converting all invalid elements of the ID into __ASCIICODE__ elements, which can then be converted back.

As mentioned, my aim is to store model IDs in annotation fields, as an SBML ID is, by definition, not intended to be used as a readable identifier.

**Comment by BenjaSanchez** [comment]
@tpfau that sounds great, i assume once that is done we could use any format we want for our model ids and they would be stored literally?

**Comment by Midnighter** [comment]
@matthiaskoenig how would this be handled in https://github.com/opencobra/cobrapy/pull/685?

**Comment by matthiaskoenig** [comment]
> How it should be opened by cobrapy: s_0001_c

This is completely subjective (or is there any reference document which says so). There is no defined way of which replacements should be performed. COBRA has to write valid SBML ids, these are than read exactly in cobrapy.

The new parser provides replacement dictionaries you can provide which are than applied to the identifiers, so everybody can perform SBML id transformation in the way he/she thinks it should be.

**Comment by BenjaSanchez** [comment]
@matthiaskoenig maybe the frasing sounded harsh on cobrapy, what i meant is how it should be opened for **our model**, i.e. how we would like cobrapy to open it (not implying that there's a problem with cobrapy, which does what it should; that is why this issue is in this repo and not in cobrapy nor COBRA toolbox). For now we will just write a wrapper that does the conversion, and I'm looking forward to the release of the new parser!

Thank you all @tpfau @Midnighter @matthiaskoenig

**Comment by matthiaskoenig** [comment]
No problem. 
I answered a bit harsh, because I personally think replacements of ids create a ton of issues and should never be performed. Basically all data you map in the SBML ids cannot be mapped any more. Many of the replacements are irreversible (no roundtripping possibe). Also you can have a ton of side effects if you are unlucky and the same string occurs in your id. For instance there are also some '[' sometimes in the id and not only in the compartment attachment. 

To achieve what you want you would just provide a replacement dictionary to the parser.
```
replace_dict = {
  '__91__':  '_',
  '__93__': '',
}
```
