### ISSUE TITLE
duplicated reactions

### ISSUE THREAD

**Issue by snmendoz** [SysBioChalmers/yeast-GEM#187]
### Description of the issue:
@BenjaSanchez I found 5 duplicated reactions. They are the same but written in the opposite direction. 

1) 'r_2115'	'r_0163'
'1 s_0359[c] + 1 s_0794[c] + 1 s_1203[c] -> 1 s_0680[c] + 1 s_1198[c]'	
'1 s_0680[c] + 1 s_1198[c] -> 1 s_0359[c] + 1 s_0794[c] + 1 s_1203[c]'

2) 'r_0919'	'r_0342'
'1 s_1085[er] + 1 s_1366[er] -> 1 s_0481[er]'	
'1 s_0481[er] -> 1 s_1085[er] + 1 s_1366[er]'

3) 'r_0920'	'r_0343'
'1 s_0507[er] + 1 s_1366[er] -> 1 s_0484[er]'	
'1 s_0484[er] -> 1 s_0507[er] + 1 s_1366[er]'

4) 'r_1760'	'r_1148'
'1 s_0666[c] <=> 1 s_0665[ce]'	
'1 s_0665[ce] <=> 1 s_0666[c]'

5) 'r_4566'	'r_4232'
'1 s_0340[c] + 1 s_0394[c] + 1 s_0794[c] -> 1 s_0434[c] + 1 s_3875[c]'	
'1 s_0434[c] + 1 s_3875[c] -> 1 s_0340[c] + 1 s_0394[c] + 1 s_0794[c]'

I would suggest to remove one of each pair of duplicated reactions and change to reversible the reaction that is kept. 

This new issue is in relation with the issue #172. It is important to avoid duplicated reactions because it would facilites the translation of the model to BIGG identifiers. 

If there is a particular reason to keep these duplicated reactions? If there is can handle them for the translation to BIGG identifiers (#172). Please, tell me what you think or decide. 

If you agree, please assign this task to me

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
@snmendoz no need imo to keep these duplicated rxns, any thoughts @hongzhonglu @feiranl?

**Comment by hongzhonglu** [comment]
@snmendoz @BenjaSanchez  Are the enzyme ( or gene) is same for these duplicated reactions?

**Comment by snmendoz** [comment]
@BenjaSanchez @hongzhonglu 

No, they have different gene-associations. Maybe that's why they were included in this way in the first place.

**Comment by BenjaSanchez** [comment]
@snmendoz @hongzhonglu then when merging remember to also combine both `grRules` with "or" associations

**Comment by hongzhonglu** [comment]
@snmendoz @BenjaSanchez  Not sure whether they can merged as different genes were connected for these duplicated reactions.

**Comment by BenjaSanchez** [comment]
adding to this discussion other duplicate rxns found by @hvdinh16

> r_4235: duplicate of r_0534
> r_4236: lumped reaction, duplicate of r_0697 + r_0553
> r_4264: potential duplicate of r_0454

**Comment by BenjaSanchez** [comment]
Coming back to this, wrt to the 5 cases that @snmendoz pointed out, I agree with @hongzhonglu that if they have different gene rules then both of them should stay. From all 5 reactions, only 1 of them is a true duplicate, see below all info available for each one in the `.yml` file:
![image](https://user-images.githubusercontent.com/9384349/80370909-4eafc900-8891-11ea-985c-c709b633f858.png)
So I think we can delete `r_1760` from the model, will do that in PR #188. @hongzhonglu let me know what you think.

wrt to the 3 cases that  @hvdinh16 pointed out:

* `r_4235/r_0534`: This one indeed seems to be a duplicate, the only stoichiometric difference is in that `r_0534` is mass balanced so it has a proton (`s_0794`):
  ![image](https://user-images.githubusercontent.com/9384349/80384152-d2bf7c00-88a4-11ea-9fb4-48ca0cc812e7.png)
  so I can just add `YDR516C` to the gene rule of `r_0534` and then delete `r_4235`, also in PR #188. @feiranl @hongzhonglu thoughts?

* `r_4236/r_0697+r_0553`: Here for simplicity I would keep all three, as the lumped one has several genes that otherwise we would loose, but as far as I could tell those genes were not associated to any of the two steps of the reaction, e.g. [`YDR533C`](https://www.yeastgenome.org/locus/S000002941) (part of the `r_4236` gene rule) is just described as "Methylglyoxalase that converts methylglyoxal to D-lactate", whereas [`YML004C`]() (controling `r_0697`) is described as "Monomeric glyoxalase I; catalyzes the detoxification of methylglyoxal (a by-product of glycolysis) via condensation with glutathione to produce S-D-lactoylglutathione".

* `r_4264/r_0454`: These are different reactions entirely, as one uses `NADH` as cofactor and the other one `FADH2`. So both should stay.
