### ISSUE TITLE
fix: zero-growth in anaerobic conditions

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#198]
### Description of the issue:

The model is currently not able to grow anaerobically, which is most likely due to the inclusion of several cofactors to the biomass composition (PR #174). We should find which cofactors are the culprit and adapt the function `anaerobicModel.m` to omit those cofactors, as it is already done with `heme a`.

#### Reproducing these results:

```matlab
model = loadYeastModel;
anaerobicModel
sol = optimizeCbModel(model);
```

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by feiranl** [comment]
Yes, this problem is due to that we adding cofactors in the model. We addressed the problem locally before, and will be uploaded soon.

**Comment by BenjaSanchez** [comment]
@feiranl any progress here? in the meantime could you indicate here which cofactors are the responsibles for no growth, so to inform people that may wish to use the model anaerobically?

**Comment by BenjaSanchez** [comment]
update: this has been fixed in #199 by removing `NAD`, `NADP`, `NADPH` and `NADH` from the biomass equation for anaerobic conditions. This issue will be closed on the next release

**Comment by feiranl** [comment]
We identified that [coenzyme A](https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PANTO-PWY) also requires oxygen due to oxygen requirement of precursor [beta-alanine](https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5760). However, due to missing coA in the reaction` r_4571	2-hydroxyglutarate [cytoplasm] 	<=>	glyoxylate [cytoplasm] + 3 H+ [cytoplasm] + propionyl-CoA [cytoplasm] ` and  it will generate coA unlimitedly. We should remove coA also from the anaerobic growth. Thanks Eiden @eiden309 for pointing out the missing coA in the reaction r_4571. Will be fixed in the future.

**Comment by BenjaSanchez** [comment]
@feiranl the bigger issue then would be to solve the CoA balancing of that reaction though, could you open an issue for that?

**Comment by edkerk** [comment]
> @feiranl the bigger issue then would be to solve the CoA balancing of that reaction though, could you open an issue for that?

This is being done by @eiden309 as part of #194, should be committed to GitHub soon.

**Comment by feiranl** [comment]
Yes, it will be balanced in the #194.
