### ISSUE TITLE
previous versions of yeast - no gpr

### ISSUE THREAD

**Issue by yseif** [SysBioChalmers/yeast-GEM#204]
I'm trying to load previous versions of the yeast models (yeast1, yeast2, and yeast3, obtained from https://sourceforge.net/projects/yeast/files/), using the cobrapy command cobra.io.read_sbml_model() but it seems as though there are no GPRs in these models.

This issue does not affect the subsequent versions of yeast. Do you happen to have these models with associated GPRs?

**Comment by BenjaSanchez** [comment]
@yseif here we only maintain yeast7.6 onwards, so we do not have those versions, sorry. However I quickly looked into the yeast1 sbml file from sourceforge and it seems that they have stored gene information in the reaction `name` field, e.g.:

```xml
<reaction metaid="metaid_R_1822" id="R_1822" name="YEL039C, YKR066C" sboTerm="SBO:0000176">
```

So maybe look into your reaction names instead of GPRs in cobrapy. Not sure if this is the case for all gene rules, but perhaps it is comparable with more recent versions of the model?  Do let us know through here, and if this is also true for yeast2 and yeast3.
