### ISSUE TITLE
KEGG reaction annotations

### ISSUE THREAD

**Issue by HnCetin** [SysBioChalmers/yeast-GEM#205]
### Description of the issue:
While I was checking the reactions with a confidence score lower than `3`, I've found that some of the reactions with KEGG ID's are not the same as shown in KEGG Reactions database. You can see the list below where I separated them with lines for a cleaner look.

Please note that I am not 100% sure about my suggestions. Please treat the list below as questions.

### List of Reactions:
-  **`r_0911`**: Reaction takes ATP as a substrate in yeastGEM
`5'-phosphoribosyl-5-aminoimidazole[c]   + ATP[c] + carbon dioxide[c] + H2O[c] => ADP[c] + H+[c] + phosphate[c] +   phosphoribosyl-carboxy-aminoimidazole[c]`

-  **`R04209`** : No ATP in the substrates.
`1-(5-Phospho-D-ribosyl)-5-amino-4-imidazolecarboxylate <=> Aminoimidazole ribotide + CO2`

I've checked other databases for this reaction and found that [MetaCyc](https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=AIRCARBOXY-RXN) and [ModelSEED](http://modelseed.org/biochem/reactions/rxn02938) are in agreement with [KEGG](https://www.genome.jp/dbget-bin/www_bget?R04209), on the other hand, [UniProt](https://www.uniprot.org/uniprot/P50504) says the enzyme has a binding site for ATP. There is also another model in [BiGG](http://bigg.ucsd.edu/models/iYL1228/reactions/AIRC2) (iYL1228) with ATP in the substrates. I wonder that if you put ATP to substrates in order to create a demand for it, or how did you decide.

-------
-  **`r_0774`** & **`r_0775 for [m]`** : No ATP in the yeastGEM 
`H+[c] +   nicotinate[c] + PRPP[c] => diphosphate[c] + nicotinic acid   D-ribonucleotide[c]`

-   **`R01724`** : Reaction requires ATP in the [KEGG](https://www.genome.jp/dbget-bin/www_bget?R01724)
` Nicotinate D-ribonucleotide + Diphosphate + ADP + Orthophosphate <=> Nicotinate + 5-Phospho-alpha-D-ribose 1-diphosphate + ATP + H2O + H+`

Note that the reactions are in the opposite directions. Same as the previous one, different reactions exist in different databases: According to [MetaCyc](https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=NICOTINATEPRIBOSYLTRANS-RXN), reaction should include ATP. On the other hand, [ModelSEED](http://modelseed.org/biochem/reactions/rxn01265) and [BiGG](http://bigg.ucsd.edu/universal/reactions/NAPRT) say the opposite.

-------

- **`r_0198`** : alpha-glucosidase (EC 3.2.1.10 or 3.2.1.20)
`H2O[c] + maltose[c] => 2   D-glucose[c]`

- **`R01555`** : Maltose:phosphate 1-beta-D-glucosyltransferase (EC 2.4.1.8)
`Maltose + Orthophosphate <=> D-Glucose + beta-D-Glucose 1-phosphate`

Reaction in the model is annotated with a wrong KEGG ID. It should be `R00028` (see below)  which has the same reaction and enzyme with the model.     
- **`R00028`** :  maltose glucohydrolase (EC 3.2.1.20)
`Maltose + H2O <=> 2 D-Glucose`

-------

- **`R09645`** : No such reaction with this ID exists.

- **`r_4245`** : 2-O-(6-phospho-alpha-D-mannosyl)-D-glycerate 6-phosphomannohydrolase 
`H2O[v] +   2-O-(6-phospho-alpha-D-mannosyl)-D-glycerate[v] => D-mannose   6-phosphate[v] + D-Glycerate[v]`

Annotated enzyme has a page in [KEGG](https://www.genome.jp/dbget-bin/www_bget?ec:3.2.1.24) however reactions are not exactly the same.

-------

- **`r_2116`**:  acetaldehyde dehydrogenase (1.2.1.3)
`acetaldehyde[c] + H2O[c] + NAD[c] => acetate[c] + H+[c] + NADH[c]`

- **`R00711`**:  Acetaldehyde:NADP+ oxidoreductase (EC 1.2.1.4 or 1.2.1.5  )
`Acetaldehyde + NADP+ + H2O <=> Acetate + NADPH + H+`

`r_2116` should be annotated with `R00710` (reaction below) as the same as `r_0174` (mitochondrial version of `r_2116`).

-  **`R00710`**: Acetaldehyde:NAD+ oxidoreductase (EC 1.2.1.3 or 1.2.1.5)
`Acetaldehyde + NAD+ + H2O <=> Acetate + NADH + H+`

-----

-  **`r_4254`** : nitric oxide, NADPH2:oxygen   oxidoreductase 
`NADH[c] + 2 oxygen[c] + 2 nitric   oxide[c] => H+[c] + NAD[c] + 2 nitrate[c] `

-  **`r_4255`** : Flavohemoprotein (EC 1.14.12.17) (Flavohemoglobin)   (Hemoglobin-like protein) (Nitric oxide dioxygenase) (NO oxygenase) (NOD) 
`NADPH[c] + 2 oxygen[c] + 2 nitric oxide[c] => H+[c] +   NADP(+)[c] + 2 nitrate[c]`

Both of these reactions have the KEGG ID `R05725` (reaction below). They have the same enzyme and gene annotations. I believe the first one is an unintentional duplicate with a wrong metabolite.

-  **`R05725`** : nitric oxide, NADPH2:oxygen oxidoreductase
`2 Nitric oxide + 2 Oxygen + NADPH + H+ <=> 2 Nitrate + NADP+`

-----
-  **`r_0241`** : C-4 sterol methyl oxidase (4,4-dimethylzymosterol)
`14-demethyllanosterol[c] + 3 H+[c] + 3 NADPH[c] + 3 oxygen[c] => 4beta-methylzymosterol-4alpha-carboxylic acid[c] + 4 H2O[c] + 3 NADP(+)[c]`

-  **`R07509`** : 14-demethyllanosterol,ferrocytochrome-b5:oxygen oxidoreductase (hydroxylating)
`14-Demethyllanosterol + 6 Ferrocytochrome b5 + 3 Oxygen + 6 H+ <=> 4alpha-Methylzymosterol-4-carboxylate + 6 Ferricytochrome b5 + 4 H2O`

Since `Ferricytochrome b5` exists in the metabolites (used in the reactions `r_4196` and `r_4197`) and assuming from the lower ID of the `r_0241`, the `NADP` could have been changed to `Ferricytochrome b5`. I am not sure about the reaction specifically, but it is possible that it might be overlooked when the metabolite added to the model. 

-----

#### A finishing note:
While having a KEGG ID for each reaction is a big plus to fetch data automatically, these small differences can create overlooking problems as the model grows. I have plans to check reactions with a confidence score of `3` individually, so I will let you know soon. Sorry if the lines create mess, my intentions were good.

I hope these can help.

Best regards,
Handan

**I hereby confirm that I have:**
- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by hongzhonglu** [comment]
@HnCetin  Thanks a lot. Very nice suggestion! It will be nice to check all the reactions with kegg id in the current model to improve the quality. Do you plan to check reactions with other confidence scores?

**Comment by HnCetin** [comment]
@hongzhonglu I plan to check reactions with KEGG ids for other confidence scores, yet I am not really sure that it is going to be helpful. Unless I have a solution on how to decide which reactions to include in the model (for the reactions where different databases show different substrates), I probably will not continue. So far, I am doing literature searching for the reactions or enzymes for their binding sites. If you have any other suggestions, I will be happy to take them.

**Comment by hongzhonglu** [comment]
@HnCetin  It is possible that a reaction could be in different formula as the related enzyme could have multiple functions. I think in this case, we should refer to the gene function annotation based on the UniProt or SGD.

**Comment by BenjaSanchez** [comment]
@eiden309 have all issues here been addressed after merging #220?

**Comment by eiden309** [comment]
@BenjaSanchez only issues related to KEGG annotations (r_0198, r_0911, r_4245, r_2116, r_4254 and r_4255) were resolved in #220.

**These are the changes made after reviewing the comments by @HnCetin and discussing with @edkerk and @feiranl (I will include these in #220 as well):**
Reactions | Notes
-- | --
`r_0198` | Edited as suggested - changed model.rxnKEGGID to [R00028](https://www.kegg.jp/dbget-bin/www_bget?rn:R00028) |  
`r_0911` | With reference to module [M00048](https://www.genome.jp/kegg-bin/show_module?M00048+R04209), there is another pathway [R07404](https://www.genome.jp/dbget-bin/www_bget?R07404) and [R07405](https://www.genome.jp/dbget-bin/www_bget?R07405) which requires ATP as a substrate. [R04209](https://www.kegg.jp/dbget-bin/www_bget?rn:R04209) has been removed from `r_0911` since it is an incorrect reaction annotation. However, this remains an issue as there is no way of incorporating 2 rxnKEGGIDs ([R07404](https://www.genome.jp/dbget-bin/www_bget?R07404) and [R07405](https://www.genome.jp/dbget-bin/www_bget?R07405)) into the model |  
`r_4245` | `R09645` removed from the model since it cannot be found in KEGG, as mentioned. |  
`r_2116` | Edited as suggested - changed model.rxnKEGGID to [R00710](https://www.kegg.jp/dbget-bin/www_bget?rn:R00710)|  
`r_4254` | Changed model.rxnKEGGID to [R05724](https://www.kegg.jp/dbget-bin/www_bget?rn:R05724) and model.rxnName to `nitric oxide,   NADH2:oxygen oxidoreductase` |  
`r_4255` | Changed model.rxnName to `nitric oxide, NADPH2:oxygen oxidoreductase`

**The remaining reactions were reviewed but have not been modified (I will amend these next week):**
Reactions | Notes
-- | --
`r_0774` and `r_0775`  | Should include ATP/ADP in the reactions since [MNXR101909](https://www.metanetx.org/equa_info/MNXR101909) and [P39683](https://www.uniprot.org/uniprot/P39683) have also annotated reactions with ATP/ADP |
`r_0241` | Should edit as suggested - change NADPH/NADP(+) to Ferrocytochrome b5/Ferricytochrome b5 |
