### ISSUE TITLE
feat: volatiles produced by S. cerevisiae

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/yeast-GEM#296]
### Description of the issue:
* Model expansion to cover more volatiles as metabolites.

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by feiranl** [comment]
Reactions from [this paper](https://www.mdpi.com/2227-9717/8/9/1195/htm) should also checked and curated into the Yeast8?

**Comment by edkerk** [comment]
@wtscott31 That's your paper, is this included in #300 ?

**Comment by wtscott31** [comment]
Yes I already added pathways related to my paper into Yeast8 in PR #248
https://github.com/SysBioChalmers/yeast-GEM/pull/248
This new PR is based on new literature about sulfur metabolism.

**Comment by uliebal** [comment]
I am joining @Hendrik-iAMB to add volatile reactions to the model on a new [fork](https://github.com/iAMB-RWTH-Aachen/yeast-GEM-iAMBvolatiles). Some questions:
1. Should I really use the `main` branch in my fork as mentioned by @feiranl? The developers guide recommends a `develop`-branch.
2. I would like to work in Python and add reactions to get a new `xml`. How do I generate the corresponding `yml` and `txt` file versions?
3. How should I choose new reaction and metabolite IDs?

**Comment by mihai-sysbio** [comment]
> I am joining @Hendrik-iAMB to add volatile reactions to the model on a new [fork](https://github.com/iAMB-RWTH-Aachen/yeast-GEM-iAMBvolatiles).

Excellent!

>     1. Should I really use the `main` branch in my fork as mentioned by @feiranl? The developers guide recommends a `develop`-branch.

Since I can't find the context in which @feiranl might have said this, I can only second the developers guide even if `develop` is [quite close to `main` at the moment](https://github.com/SysBioChalmers/yeast-GEM/compare/develop...main), that is bound to change.

>     2. I would like to work in Python and add reactions to get a new `xml`. How do I generate the corresponding `yml` and `txt` file versions?

Perhaps a Matlab user can contribute to your fork by using the corresponding function in RAVEN (`exportYaml`, `exportModel`).

>     3. How should I choose new reaction and metabolite IDs?

That's a great question to have, and what I believe to be the right answer doesn't have its place here. The next best thing that I can recommend is to "borrow" an identifier from another database (like it was done with BiGG ids). This would defer the renaming of the ids to an indefinite future (a great time would be the next major release).

**Comment by edkerk** [comment]
Included in #339
